source "https://rubygems.org"

# GitHub Pages gem
gem "github-pages", group: :jekyll_plugins

# Jekyll and plugins
gem "jekyll", "~> 3.9.0"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.3"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-relative-links", "~> 0.6"

# Theme
gem "minima", "~> 2.5"

# Development
gem "webrick", "~> 1.7"

# Windows and JRuby does not include zoneinfo files
gem "tzinfo", "~> 1.2"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :mswin, :x64_mingw, :jruby]